{
 "title": "International CW Beacon Monitor",
 "tags": [ "home" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Calls heard",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\n  |> group(columns: [\"call\"])\n  |> count()\n  |> group()\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Calls heard t-1d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> group(columns: [\"call\"])\r\n  |> count()\r\n  |> group()\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Highest SNR/Band for selected TIme range",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 4 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: max)\r\n  |> group(columns: [\"monitor_id\"])\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Beacons heard over time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "duration = if (uint(v: v.timeRangeStop) -  uint(v: v.timeRangeStart)) > 3600*24*1000*1000*1000*2 then 1d else 1h\n\nfrom(bucket: \"hb9cu\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"measurement\")\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\n  |> group(columns: [\"call\"])\n  |> aggregateWindow(every:duration, fn: max)\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:r._field}))\n  |> group(columns: [\"_time\"])\n  |> count()\n  |> group()\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: \"Beacons heard\"}))\n  |> keep(columns: [\"_value\", \"_time\", \"_field\"])\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OH2B - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 33 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"OH2B\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OH2B - Lohja Finland - 1700 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"OH2B\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CS3B - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 45 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"CS3B\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CS3B - São Jorge Madeira - 2700 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"CS3B\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4X6TU - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 57 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"4X6TU\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4X6TU - Tel Aviv Israel - 2800 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"4X6TU\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RR9O - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 69 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"RR9O\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RR9O - Novosibirsk Russia - 4800 km",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"RR9O\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VE8AT - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 82 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"VE8AT\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VE8AT - Eureka Canada - 4900km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"VE8AT\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "5Z4B - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 94 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"5Z4B\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "5Z4B - Kariobangi Kenya - 6000km",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"5Z4B\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4U1UN - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 105 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"4U1UN\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4U1UN - New York City USA - 6300 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"beacon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"4U1UN\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4S7B - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 117 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"4S7B\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "4S7B - Colombo Sri Lanka - 8000 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"4S7B\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "YV5B - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 129 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"YV5B\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "YV5B - Caracas Venezuela - 8100 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"YV5B\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ZS6DN - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 141 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"ZS6DN\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ZS6DN - Pretoria South Africa - 8400 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"ZS6DN\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VR2B - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 153 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"VR2B\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VR2B - Hong Kong - 9300 km",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 17, "x": 7, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"VR2B\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "W6WX - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 166 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"W6WX\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "W6WX - Mt. Umunhum USA - 9400 km",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"W6WX\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JA2IGY - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 176 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"JA2IGY\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JA2IGY - Mt. Asama Japan - 9600 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"JA2IGY\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OA4B - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 188 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"OA4B\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OA4B - Lima Peru - 10700 km",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"OA4B\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LU4AA - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 199 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"LU4AA\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LU4AA - Buenos Aires Argentina  - 11400 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"LU4AA\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "KH6RS - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 211 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"KH6RS\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "KH6RS - Maui Hawaii  - 12300 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 211 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"KH6RS\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VK6RBP - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 223 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"VK6RBP\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VK6RBP - Roleystone Australia  - 13800 km",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"VK6RBP\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ZL6B - Last SNR",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 235 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"ZL6B\")\r\n  |> group(columns: [\"call\"])\r\n  |> sort(columns:[\"_time\"])\r\n  |> aggregateWindow(every: 30d, fn: last)\r\n  |> keep(columns: [\"_value\", \"geohash\", \"call\", \"monitor_id\", \"mhz\"])\r\n  |> map(fn: (r) => ({r with name: r.call +\" (\" + r.mhz + \"mhz)\"}))\r\n  |> yield(name: \"beacon\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ZL6B - Masterton New Zealand  - 18800 km",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"hb9cu\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"snr\")\r\n  |> filter(fn: (r) => r[\"call\"] == \"ZL6B\")\r\n  |> sort(columns:[\"mhz\"])\r\n  |> aggregateWindow(every: 1m, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.mhz+\" mhz\" }))\r\n  |> keep(columns:[\"_field\", \"_time\", \"_value\"])\r\n  |> yield(name: \"max\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}